 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/blacklisted_auth_tokens", type: :request do
  # BlacklistedAuthToken. As you add validations to BlacklistedAuthToken, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BlacklistedAuthToken.create! valid_attributes
      get blacklisted_auth_tokens_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      blacklisted_auth_token = BlacklistedAuthToken.create! valid_attributes
      get blacklisted_auth_token_url(blacklisted_auth_token)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_blacklisted_auth_token_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      blacklisted_auth_token = BlacklistedAuthToken.create! valid_attributes
      get edit_blacklisted_auth_token_url(blacklisted_auth_token)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BlacklistedAuthToken" do
        expect {
          post blacklisted_auth_tokens_url, params: { blacklisted_auth_token: valid_attributes }
        }.to change(BlacklistedAuthToken, :count).by(1)
      end

      it "redirects to the created blacklisted_auth_token" do
        post blacklisted_auth_tokens_url, params: { blacklisted_auth_token: valid_attributes }
        expect(response).to redirect_to(blacklisted_auth_token_url(BlacklistedAuthToken.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BlacklistedAuthToken" do
        expect {
          post blacklisted_auth_tokens_url, params: { blacklisted_auth_token: invalid_attributes }
        }.to change(BlacklistedAuthToken, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post blacklisted_auth_tokens_url, params: { blacklisted_auth_token: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blacklisted_auth_token" do
        blacklisted_auth_token = BlacklistedAuthToken.create! valid_attributes
        patch blacklisted_auth_token_url(blacklisted_auth_token), params: { blacklisted_auth_token: new_attributes }
        blacklisted_auth_token.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the blacklisted_auth_token" do
        blacklisted_auth_token = BlacklistedAuthToken.create! valid_attributes
        patch blacklisted_auth_token_url(blacklisted_auth_token), params: { blacklisted_auth_token: new_attributes }
        blacklisted_auth_token.reload
        expect(response).to redirect_to(blacklisted_auth_token_url(blacklisted_auth_token))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        blacklisted_auth_token = BlacklistedAuthToken.create! valid_attributes
        patch blacklisted_auth_token_url(blacklisted_auth_token), params: { blacklisted_auth_token: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested blacklisted_auth_token" do
      blacklisted_auth_token = BlacklistedAuthToken.create! valid_attributes
      expect {
        delete blacklisted_auth_token_url(blacklisted_auth_token)
      }.to change(BlacklistedAuthToken, :count).by(-1)
    end

    it "redirects to the blacklisted_auth_tokens list" do
      blacklisted_auth_token = BlacklistedAuthToken.create! valid_attributes
      delete blacklisted_auth_token_url(blacklisted_auth_token)
      expect(response).to redirect_to(blacklisted_auth_tokens_url)
    end
  end
end
