 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/refresh_auth_tokens", type: :request do
  # RefreshAuthToken. As you add validations to RefreshAuthToken, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RefreshAuthToken.create! valid_attributes
      get refresh_auth_tokens_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      refresh_auth_token = RefreshAuthToken.create! valid_attributes
      get refresh_auth_token_url(refresh_auth_token)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_refresh_auth_token_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      refresh_auth_token = RefreshAuthToken.create! valid_attributes
      get edit_refresh_auth_token_url(refresh_auth_token)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RefreshAuthToken" do
        expect {
          post refresh_auth_tokens_url, params: { refresh_auth_token: valid_attributes }
        }.to change(RefreshAuthToken, :count).by(1)
      end

      it "redirects to the created refresh_auth_token" do
        post refresh_auth_tokens_url, params: { refresh_auth_token: valid_attributes }
        expect(response).to redirect_to(refresh_auth_token_url(RefreshAuthToken.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RefreshAuthToken" do
        expect {
          post refresh_auth_tokens_url, params: { refresh_auth_token: invalid_attributes }
        }.to change(RefreshAuthToken, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post refresh_auth_tokens_url, params: { refresh_auth_token: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested refresh_auth_token" do
        refresh_auth_token = RefreshAuthToken.create! valid_attributes
        patch refresh_auth_token_url(refresh_auth_token), params: { refresh_auth_token: new_attributes }
        refresh_auth_token.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the refresh_auth_token" do
        refresh_auth_token = RefreshAuthToken.create! valid_attributes
        patch refresh_auth_token_url(refresh_auth_token), params: { refresh_auth_token: new_attributes }
        refresh_auth_token.reload
        expect(response).to redirect_to(refresh_auth_token_url(refresh_auth_token))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        refresh_auth_token = RefreshAuthToken.create! valid_attributes
        patch refresh_auth_token_url(refresh_auth_token), params: { refresh_auth_token: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested refresh_auth_token" do
      refresh_auth_token = RefreshAuthToken.create! valid_attributes
      expect {
        delete refresh_auth_token_url(refresh_auth_token)
      }.to change(RefreshAuthToken, :count).by(-1)
    end

    it "redirects to the refresh_auth_tokens list" do
      refresh_auth_token = RefreshAuthToken.create! valid_attributes
      delete refresh_auth_token_url(refresh_auth_token)
      expect(response).to redirect_to(refresh_auth_tokens_url)
    end
  end
end
