default: &default
  adapter: mysql2
  socket: /tmp/mysql.sock
  encoding: utf8mb4
  host: 127.0.0.1
  pool: 5

development:
  <<: *default
  database: assignment_development
  username: root
  password: your_password
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: assignment_test
  username: root
  password: your_password
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= ENV["ASSIGNMENT_DATABASE_NAME"] %>
  username: <%= ENV["ASSIGNMENT_USER_NAME"] %>
  password: <%= ENV["ASSIGNMENT_PASSWORD"] %>
